import type { Metadata } from "next";
import { Pacifico, PT_Sans_Narrow } from "next/font/google";
import Header from "@/components/common/header";
import Footer from "@/components/common/footer";

import { getAllProducts } from "@/lib/server/queries";
import StoreProvider from "../providers/store-provider";
import { ToastContainer } from "react-toastify";

import "./globals.css";
import ReactQueryProvider from "@/providers/react-query-provider";

const ptSansNarrow = PT_Sans_Narrow({
  subsets: ["latin"],
  weight: ["400", "700"],
  fallback: ["sans-serif"],
});
const pacifico = Pacifico({
  variable: "--font-pacifico",
  subsets: ["cyrillic"],
  weight: ["400"],
  fallback: ["Sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const products = await getAllProducts();

  return (
    <html lang="en">
      <body
        className={`${ptSansNarrow.className} ${pacifico.variable}  antialiased`}
      >
        <StoreProvider>
          <ToastContainer closeOnClick pauseOnHover />
          <ReactQueryProvider>
            <Header products={products} />
            {children}
            <Footer />
          </ReactQueryProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
