import CategoriesSection from "./_components/sections/categories-section";
import HeroSection from "./_components/sections/hero-section";
import IntroSection from "./_components/sections/intro-section";
import MenuSection from "./_components/sections/menu-section";
import BookTableSection from "../../components/common/sections/book-table-section";
import BestChefSection from "./_components/sections/best-chef-section";
import ReviewsSection from "../../components/common/sections/reviews-section";
import AboutSection from "./_components/sections/about-section";

import { Metadata } from "next";
import { getAllCategories } from "@/lib/server/queries";
import { getQueryClient } from "@/providers/react-query-provider/get-query-client";
import { getProductsByPage } from "@/lib/queries/product/get-products-by-page";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};
export default async function Home() {
  const categories = await getAllCategories();
  const queryClient = getQueryClient();

  void queryClient.prefetchQuery({
    queryKey: ["products"],
    queryFn: async () => await getProductsByPage(),
  });

  return (
    <main className="min-h-screen">
      <HeroSection />
      <IntroSection />
      <CategoriesSection categories={categories} />
      <MenuSection categories={categories} />
      <BookTableSection />
      <BestChefSection />
      <ReviewsSection />
      <AboutSection />
    </main>
  );
}
